# Generated by Django 4.1.6 on 2023-02-10 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='створено'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='overview',
            field=models.TextField(verbose_name='огляд'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=200, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='назва'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='назва')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='оновлено')),
                ('url', models.URLField(verbose_name='Відео')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='назва')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='оновлено')),
                ('content', models.TextField(verbose_name='зміст')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='назва')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='оновлено')),
                ('file', models.FileField(upload_to='images', verbose_name='зображення')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='назва')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='оновлено')),
                ('file', models.FileField(upload_to='files', verbose_name='файл')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name="ідентифікатор об'єкта")),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.module')),
            ],
        ),
    ]
